### ISSUE TITLE
Gamecrash(crash report below)

### ISSUE THREAD

**Issue by Alphapowers777** [Mindoth/fabledweaponry#2]
---- Minecraft Crash Report ----
// My bad.

Time: 2024-05-13 20:13:01
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.105-universal.jar%23247!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.1.105-universal.jar%23247!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:tslatentitystatus.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:tslatentitystatus.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:148) ~[forge-1.20.1-47.1.105-universal.jar%23247!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:958) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:tslatentitystatus.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:tslatentitystatus.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.105.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
-- MOD fabledweaponry --
Details:
	Mod File: /C:/Users/power/AppData/Roaming/.minecraft/mods/fabledweaponry-1.20.1-1.0.7.4.jar
	Failure message: Fabled Weaponry (fabledweaponry) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 1.20.1-1.0.7.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:64) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.mindoth.fabledweaponry.util.ModItemProperties.makeBow(ModItemProperties.java:46) ~[fabledweaponry-1.20.1-1.0.7.4.jar%23219!/:1.20.1-1.0.7.4] {re:classloading}
	at net.mindoth.fabledweaponry.util.ModItemProperties.addCustomItemProperties(ModItemProperties.java:13) ~[fabledweaponry-1.20.1-1.0.7.4.jar%23219!/:1.20.1-1.0.7.4] {re:classloading}
	at net.mindoth.fabledweaponry.FabledWeaponryClient.clientSetup(FabledWeaponryClient.java:15) ~[fabledweaponry-1.20.1-1.0.7.4.jar%23219!/:1.20.1-1.0.7.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2389!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2389!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2389!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2389!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:151) ~[language-java-47.2.2.jar%23244!/:47.2] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[core-47.2.2.jar%23243!/:47.2] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 413326136 bytes (394 MiB) / 1241513984 bytes (1184 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1c81
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5244
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18744.97
	Virtual memory used (MB): 10052.95
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 100.64
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		loader-47.2.2.jar slf4jfixer PLUGINSERVICE 
		loader-47.2.2.jar object_holder_definalize PLUGINSERVICE 
		loader-47.2.2.jar runtime_enum_extender PLUGINSERVICE 
		loader-47.2.2.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		loader-47.2.2.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		lowcodefml@47.2
		minecraft@47.2
		javafml@47.2
	Mod List: 
		TES-neoforge-1.20.1-1.5.1.jar                     |TES                           |tslatentitystatus             |1.5.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		skillcloaks-1.20.1-1.2.2 (1).jar                  |Skillcloaks                   |skillcloaks                   |1.20.1-1.2.2        |ENQUEUE_IM|Manifest: NOSIGNATURE
		geckolib-neoforge-1.20.1-4.4.2.jar                |GeckoLib 4                    |geckolib                      |4.4.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20 (4).jar |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |ENQUEUE_IM|Manifest: NOSIGNATURE
		caelus-forge-3.1.0+1.20 (2).jar                   |Caelus API                    |caelus                        |3.1.0+1.20          |ENQUEUE_IM|Manifest: NOSIGNATURE
		invtweaks-1.20.1-1.0.0.jar                        |Inventory Tweaks Refoxed      |invtweaks                     |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.3.jar                   |Waystones                     |waystones                     |14.1.3              |ENQUEUE_IM|Manifest: NOSIGNATURE
		fabledweaponry-1.20.1-1.0.7.4.jar                 |Fabled Weaponry               |fabledweaponry                |1.20.1-1.0.7.4      |ERROR     |Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.4.jar                  |Clumps                        |clumps                        |12.0.0.4            |ENQUEUE_IM|Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.21-forge.jar                |Journeymap                    |journeymap                    |5.9.21              |ENQUEUE_IM|Manifest: NOSIGNATURE
		citadel-2.5.4-1.20.1.jar                          |Citadel                       |citadel                       |2.5.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.1.10.jar                |Bookshelf                     |bookshelf                     |20.1.10             |ENQUEUE_IM|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		iceandfire-2.1.13-1.20.1-beta-4.jar               |Ice and Fire                  |iceandfire                    |2.1.13-1.20.1-beta-4|ENQUEUE_IM|Manifest: NOSIGNATURE
		Dave's Potioneering-forge-1.20.1-11.jar           |Dave's Potioneering           |davespotioneering             |11                  |ENQUEUE_IM|Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.20.1-47.1.105-universal.jar               |NeoForge                      |forge                         |47.1.105            |ENQUEUE_IM|Manifest: NOSIGNATURE
		embeddium-0.3.18+mc1.20.1-all.jar                 |Embeddium                     |embeddium                     |0.3.18+mc1.20.1     |ENQUEUE_IM|Manifest: NOSIGNATURE
		tarotcards-1.20-1.6.2.jar                         |Tarot Cards                   |tarotcards                    |1.20-1.6.2          |ENQUEUE_IM|Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4 (2).jar                   |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |ENQUEUE_IM|Manifest: NOSIGNATURE
		EquipmentCompare-1.20.1-forge-1.3.7.jar           |Equipment Compare             |equipmentcompare              |1.3.7               |ENQUEUE_IM|Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		alexscaves-1.1.4.jar                              |Alex's Caves                  |alexscaves                    |1.1.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20.1-17.0.14.jar  |EnchantmentDescriptions       |enchdesc                      |17.0.14             |ENQUEUE_IM|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		bettercombat-forge-1.8.0+1.20.1 (1).jar           |Better Combat                 |bettercombat                  |1.8.0+1.20.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		combatroll-forge-1.3.2+1.20.1.jar                 |Combat Roll                   |combatroll                    |1.3.2+1.20.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		EasierSleeping-1.20.1-2.1.3 (2).jar               |Easier Sleeping               |easier_sleeping               |2.1.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.9.1.jar                      |Jade                          |jade                          |11.9.1+forge        |ENQUEUE_IM|Manifest: NOSIGNATURE
		eeeabsmobs-1.20.1-0.8.jar                         |EEEAB's Mobs                  |eeeabsmobs                    |1.20.1-0.8          |ENQUEUE_IM|Manifest: NOSIGNATURE
		corundumguardian-2.1.2.jar                        |CorundumGuardian              |corundumguardian              |2.1.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		lionfishapi-1.8.jar                               |LionfishAPI                   |lionfishapi                   |1.8                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		L_Enders_Cataclysm-1.99.2 -1.20.1.jar             |Cataclysm Mod                 |cataclysm                     |1.99.2              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Iceberg-1.20.1-forge-1.1.21.jar                   |Iceberg                       |iceberg                       |1.1.21              |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-5.9.0+1.20.1.jar                     |Curios API                    |curios                        |5.9.0+1.20.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		shadowizardlib-1.20.1-1.0.8.jar                   |ShadowizardLib                |shadowizardlib                |1.20.1-1.0.8        |ENQUEUE_IM|Manifest: NOSIGNATURE
		gravestone-forge-1.20.1-1.0.15.jar                |Gravestone Mod                |gravestone                    |1.20.1-1.0.15       |ENQUEUE_IM|Manifest: NOSIGNATURE
		irons_spellbooks-1.20.1-3.1.5.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.20.1-3.1.5        |ENQUEUE_IM|Manifest: NOSIGNATURE
		worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |ENQUEUE_IM|Manifest: NOSIGNATURE
		constructionwand-1.20.1-2.11.jar                  |Construction Wand             |constructionwand              |1.20.1-2.11         |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-9.1.13-forge.jar                     |Architectury                  |architectury                  |9.1.13              |ENQUEUE_IM|Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1 (1).jar            |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |ENQUEUE_IM|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		PuzzlesLib-v8.1.19-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.19              |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		OverflowingBars-v8.0.0-1.20.1-Forge (2).jar       |Overflowing Bars              |overflowingbars               |8.0.0               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
	Crash Report UUID: f4692892-706e-42e3-a866-8952d711608e
	FML: 47.1
	NeoForge: net.neoforged:47.1.105

**Comment by Mindoth** [comment]
It looks like you're using NeoForge (forgive me if I'm wrong) which is not explicitly supported. I went ahead and tried to boot up a NeoForge instance with FabledWeaponry anyway and it worked fine. I even went to the same exact version I see in the crashlog (47.1.105) and still got no issues. My guess is some other mod is incompatible with this one. Try to update Forge (or NeoForge if you're indeed using that) and see if it works. If it does not then make a new instance with just FabledWeaponry. Afterwards add your mods one by one to see which one is the culprit. This won't be worked on for now but I'll keep this issue open if someone has something to add.
